server:
  port: 8080

spring:

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    initialization-mode: always

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:/db/migration
    out-of-order: false
  profiles:
    active: default
